CREATE TABLE PLAYER_SESSION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PLAYER_ID BIGINT NOT NULL,
    LOGIN_TIME TIMESTAMP,
    LOGOUT_TIME TIMESTAMP,
    FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER(ID) ON DELETE CASCADE
);
