CREATE TABLE PLAYER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    NAME VARCHAR(100),
    SURNAME VARCHAR(100),
    DATE_OF_BIRTH DATE,
    ADDRESS VARCHAR(255),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    DAILY_TIME_LIMIT_SECONDS BIGINT
);
