name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow for pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Java JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Build the application using Maven
      - name: Build with Maven
        run: ./mvnw clean install -DskipTests=true

      # Run unit tests with Maven
      - name: Run tests with Maven
        run: ./mvnw test

      - name: Upload Jar File
        uses: actions/upload-artifact@v4
        with:
            name: comeon-0.0.1-SNAPSHOT.jar
            path: build/comeon-0.0.1-SNAPSHOT.jar


  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
            name: comeon-0.0.1-SNAPSHOT.jar
            path: build/comeon-0.0.1-SNAPSHOT.jar

      # Log in to DockerHub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t deepugeorgejacob/comeon-player-service:0.0.1 .

      # Push Docker image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          docker push deepugeorgejacob/comeon-player-service:0.0.1

